spring:
  application:
    name: boombim-rabbitmq-prod

  config:
    import:
      - file:env/prod.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: root        # 기본 스키마
        jdbc:
          batch_size: 1000          # 배치 insert/update 사이즈
        order_inserts: true         # insert 정렬
        order_updates: true         # update 정렬
        batch_versioned_data: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    cache:
      channel:
        size: 50
      connection:
        mode: channel
    requested-heartbeat: 30
    connection-timeout: 5000



logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR



# Firebase FCM 설정
firebase:
  service-account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY}

admin:
  id: ${ADMIN_ID}



